name: GitHub Build PyActions
run-name: ${{ github.actor }} is Build PyActions On GitHub Actions ğŸš€
# æ‰‹åŠ¨æ„å»ºè¿è¡Œ
on:
  workflow_dispatch:
    inputs:
      build_id:
        required: true
        type: string
jobs:
  print-console:
    runs-on: ubuntu-latest
    steps:
      - run: echo "build_id is ï¼š${{ build_id }} "
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: pyinstaller --onefile hello.py
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - run: pyinstaller --onefile hello.py
  build-mac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - run: pyinstaller --onefile hello.py
